Fix for Issue #165. Documentation (README) improvements
wildfly-extras/wildfly-datasources-galleon-pack pull request #168
Opened 2022-12-09 13:42 UTC by jfdenise

2022-12-09 13:43 UTC, jfdenise commented
@bstansberry some doc improvment #168

2022-12-13 16:17 UTC, bstansberry requested changes
Very nice @jfdenise! And thanks. I had this issue on my personal todo list, but am unlikely to get to it any time soon, so much appreciated!

I've made various copy editing comments but it looks great. Please go ahead and merge when you are ready.

2022-12-13 16:17 UTC, bstansberry commented on README.md
> +For each database type its support, each feature-pack provides 3 Galleon layers that build upon each other :
s/its support/it supports/g

2022-12-13 16:17 UTC, bstansberry commented on README.md
> +* One just to add the driver (eg: `postgresql-driver`).
Perhaps add:

This installs a JBoss Modules module for the driver and adds a driver resource to the datasources subsystem in the server configuration.

2022-12-13 16:17 UTC, bstansberry commented on README.md
> +You need to include the datasources feature-pack and layers in the Maven Plugin configuration. This look like:
s/This look like/This looks like/g

or 

s/This look like/For example/g

2022-12-14 10:40 UTC, merged

2022-12-14 10:40 UTC, jfdenise commented
@bstansberry thank-you for the review. Merged with your feedback.

2022-12-14 14:10 UTC, bstansberry reviewed
Thanks, Jean-Francois. :)